spring:
  application:
    name: GARTEWAY-SERVICE

  cloud:
    gateway:
      routes:
       - id: order-service
         uri: lb://ORDER-SERVICE
         discovery:
          locator:
           predicates:
            - path=/order/**
       - id: payment-service
         uri: lb://PAYMENT-SERVICE
         discovery:
            locator:
             predicates:
              - path=/payment/**
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-ur1:
    defaultzone: http://localhost:8761/eureka/ 
    instance:
    hostname: localhost
    
    server:
    port: 8989